name: Reusable Workflow

on:
  push:

jobs:
  changes:
    uses: codeandmedia/A/.github/workflows/check.yml@main

  docker:
    needs: changes
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    uses: codeandmedia/A/.github/workflows/main.yml@main
    with:
      image_tag: ${{ github.ref_name }}
      package: ${{ matrix.package }}