name: Reusable Workflow user

on:
  push:

jobs:

  getfolders:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.dirs.outputs.test }}

    steps:
        - uses: actions/checkout@v3
        - id: dirs
          run: |
            git status .
    

  docker:
      needs: getfolders
      uses: codeandmedia/A/.github/workflows/main.yml@main
      with:
        image_tag: ${{ github.ref_name }}
        folder: ${{needs.getfolders.outputs.dirs}}
