name: Reusable Workflow user

on:
  push:

jobs:

  changes:
    runs-on: ubuntu-latest
    permissions:
      push: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'folder/**'
            frontend:
              - 'frontend/**'

  docker:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    uses: codeandmedia/A/.github/workflows/main.yml@main
    with:
      image_tag: ${{ github.ref_name }}
      folder: folder