name: Reusable Workflow user

on:
  push:

jobs:

  getfolders:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'folder/**'
            frontend:
              - 'frontend/**'

      - if: steps.filter.outputs.backend == 'true'
        uses: codeandmedia/A/.github/workflows/main.yml@main
        with:
          image_tag: ${{ github.ref_name }}
          folder: ${{ needs.get_changed.outputs.changed }}