name: Reusable Workflow user

on:
  push:

jobs:
  changes:
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    uses: codeandmedia/A/.github/workflows/check.yml@main

  docker:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    uses: codeandmedia/A/.github/workflows/main.yml@main
    with:
      image_tag: ${{ github.ref_name }}
      folder: folder